package mx.iqenglish.tutoring.entity;

public enum NotificationType {
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    TEACHER_CHANGED,
    SESSION_CANCELLED,
    GROUP_CHANGED,
    ATTENDANCE_RECORDED,
    STUDENT_ENROLLED,
    GROUP_FULL
}
