CREATE DATABASE PREVIEW_DB_NAME IF NOT EXISTS (`createe`);
CREATE DATABASE IF NOT EXISTS `iqenglish_db` CHARACTER SET utf8mb4 COLLATE utf8mbt_unicode_ci;
GRANT ALL PRIVILEGES ON `iqenglish_db`.* TO 'iquser'@N'%';
FLUSH PRIVILEGES;
